---
# in testing or production environment, a version number
# in development environment, a git branch name or commit
gisst_server_version: v0.1.0

# development only
gisst_server_dev_cargo_features: "dummy_auth"

# service
gisst_server_user: gisst
gisst_server_group: gisst
gisst_server_home: /var/lib/gisst/

# details
gisst_server_storage_dir: "{{ gisst_server_home }}/storage"
gisst_server_environment: production
gisst_server_temp_dir: "{{ gisst_server_home }}/tmp"
gisst_server_storage_dir_depth: 4

# http
gisst_server_terminate_ssl: false
gisst_server_ssl_cert: ""
gisst_server_ssl_key: ""
gisst_server_bind_address: "0.0.0.0"
gisst_server_bind_port: 3000
gisst_server_host_name: "localhost"
gisst_server_base_url: "http://{{ gisst_server_host_name }}:{{ gisst_server_bind_port }}"

# auth
# gisst_server_google_client_id: define in vault
# gisst_server_google_client_secret: define in vault

# database
gisst_server_database_full_url: "postgresql://{{ db_user_admin | default('postgres') }}:{{ db_user_admin_password | default('postgres')  }}@{{ db_host | default('127.0.0.1')  }}/{{ db_name | default('gisstdb') }}"

# metrics
gisst_server_jaeger_endpoint: "http://127.0.0.1:4317"
gisst_server_prometheus_endpoint: "http://127.0.0.1:9090"

# search
gisst_server_meilisearch_url: "{{ meilisearch_http_addr | default('http://127.0.0.1:7700') }}"
gisst_server_meilisearch_external_url: "{{ gisst_server_base_url }}/search"
