---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
- name: Restart collector
  ansible.builtin.systemd_service:
    name: jaeger
    state: restarted
- name: nginx-restart
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
  
