---
roles:
  - name: joeosborn.meilisearch
    src: https://github.com/joeosborn/ansible-role-meilisearch
    version: main
    scm: git
  - name: geerlingguy.nodejs
    version: 7.0.0
collections:
  - name: prometheus.prometheus
    version: 0.27.4
  - name: grafana.grafana
    version: 6.0.6
